### ISSUE TITLE
Lookdown Dynamic Filtering not refreshed when dependent fields change

### ISSUE THREAD

**Issue by khoait** [khoait/DCE.PCF#134]
**Component**

Lookdown v1.2.0

**Describe the bug**

Dropdown options not refreshed when dependent fields change

**Expected behavior**

Dropdown options should be filtered again after any of the dependent fields changed

**Actual behavior**

Dropdown options doesn't refresh

**Additional context**

### Discussed in https://github.com/khoait/DCE.PCF/discussions/133

**Comment by satriotsubasa** [comment]
Hi @khoait , many thanks for your incredible works. I've tried to compile this version where you fixed the dynamic filtering refresh when dependent field changed. But seems like it's still not getting refreshed:

This is the condition where I saved the changes in the form but haven't reloaded my form, as you can see the sub-category didn't return any value:
![image](https://github.com/user-attachments/assets/a3fd67c7-44a2-4850-b472-427393e9c933)

When I reloaded my form **OR** I move my active windows (example from Chrome to Windows Explorer then back to Chrome again) the values are returned correctly:
![image](https://github.com/user-attachments/assets/9d1009f6-9661-44e1-98b6-e1ac0cb2fbb3)

if you could please double check this issue again, or did I missed something in the settings?
Much appreciated, your work has been very useful.

**Comment by khoait** [comment]
Thanks @, I'll check again. Are you building from `main` branch?

**Comment by satriotsubasa** [comment]
> Thanks @, I'll check again. Are you building from `main` branch?

Yes I'm building form the `main` branch

**Comment by khoait** [comment]
@satriotsubasa yeah, there's a minor bug extracting dynamic variables. I will fix this soon and include it in the next release. thanks for checking out!

**Comment by satriotsubasa** [comment]
Hi @khoait , thanks a lot, I saw you marked this as completed and merged it to the main branch. So I tried it and re-build your source code from the  main branch. But unfortunately the dynamics filtering still not working.

**Comment by khoait** [comment]
hi @satriotsubasa, this is probably because of the component version. I fixed the bug but didn't change the component version because it's not released yet. when you import component with new code but same version, the system doesn't replace the old code with the new version.

You can fix this by removing the solution from your environment and import the new built solution again. Or you can update the component version in the manifest.xml file, build and import again, but I don't recommend this as your version will be out of synced with this repo.

**Comment by khoait** [comment]
@satriotsubasa i just built the latest release https://github.com/khoait/DCE.PCF/releases/tag/v1.1.0.0
can you try again?

**Comment by satriotsubasa** [comment]
Hi @khoait , thanks for the new release!

I just tried to remove the components from the forms, then uninstalled it from my environment, and finally import the new release solutions you just provided. 

Unfortunately the dynamics filtering still not work, the same behavior as I reported last time. When I reloaded my form OR clicked on the other active windows (example from Chrome to Windows Explorer then back to Chrome again) the values are updated correctly according to the dependent lookup field.  But when I changed dependent field without doing that, the filtering doesn't get updated.

**Comment by satriotsubasa** [comment]
Hi @khoait , after some troubleshooting, I think I found the root cause.

I'm using this XML schema for the dynamic filtering for my "City" lookup field which has dependencies with "Country" lookup field:
<filter><condition attribute="new_country" operator="eq" value="{{ new_country.id }}"/></filter>

I tried to bind this filter in a description text field, when I'm using this XML, is not working,:
![image](https://github.com/user-attachments/assets/0204faf9-9a7c-4248-8c97-c2e3b43bcb40)

But when I manually updated the country.id like below, it's working and the filtering on the "City" lookup is updated:
![image](https://github.com/user-attachments/assets/431b9b50-18f1-440c-ba97-fdbe7560a750)

I suspect that the "{{ new_country.id }}" is not being updated when we changed the dependent field (in my case is "Country"). 
I hope that helps and thanks a lot once again.

**Comment by khoait** [comment]
Thanks @satriotsubasa ! That looks like it. I'll create a new bug for this.

**Comment by satriotsubasa** [comment]
@khoait no problem at all, thanks a lot
